cloud:
  aws:
    stack:
      auto: false
    region:
      static: sa-east-1
      auto: false
    credentials:
      access-key: AKIASI6DUMMUPXH65HL3
      secret-key: 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
    end-point:
      uri: https://sqs.sa-east-1.amazonaws.com/156639716136/queue

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error